apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-config
  namespace: ecommerce
data:
  nginx.conf: |
    events {}

    http {
      sendfile on;
      client_max_body_size 10m;

      server {
        listen 80;
        server_name _;

        location /products {
          proxy_pass http://products-service:8081;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /orders {
          proxy_pass http://orders-service:8083;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /payments {
          proxy_pass http://payments-service:8082;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

      location /users {
          proxy_pass http://users-service:8084;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

        location / {
          proxy_pass http://frontend:80/;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: juanchogonza98/e-commerce:product-servicev1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: ecommerce
spec:
  selector:
    app: products-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: juanchogonza98/e-commerce:users-servicelastest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: ecommerce
spec:
  selector:
    app: users-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: juanchogonza98/e-commerce:order-servicefinal
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: PRODUCTS_API_URL
              value: "http://products-service:8081"
            - name: USERS_API_URL
              value: "http://users-service:8084"

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: ecommerce
spec:
  selector:
    app: orders-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
        - name: payments-service
          image: juanchogonza98/e-commerce:payment-servicefinish
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: ORDERS_API_URL
              value: "http://orders-service:8083"

---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: ecommerce
spec:
  selector:
    app: payments-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: juanchogonza98/e-commerce:frontendv1.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ecommerce
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
        - name: nginx-gateway
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  namespace: ecommerce
spec:
  selector:
    app: nginx-gateway
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
